# Generated by Django 5.1.4 on 2025-01-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('membership_type', models.CharField(choices=[('standard', 'Standard'), ('premium', 'Premium')], default='standard', max_length=50)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
