# Generated by Django 5.1.3 on 2025-01-30 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_gymclass_trainer_classenrollment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='image',
        ),
    ]
